
services:
  happyr.mq2php.service.message_serializer:
    class: Happyr\Mq2phpBundle\Service\MessageSerializerDecorator
    configurator: [ "@happyr.mq2php.dependency_injection.message_header_configurator" , configure]
    arguments: ["@happyr.mq2php.service.message_serializer.inner", ~]
    decorates: 'simple_bus.asynchronous.message_serializer'

  happyr.mq2php.dependency_injection.message_header_configurator:
      class: Happyr\Mq2phpBundle\DependencyInjection\Configurator\MessageHeaderConfigurator
      public: false
      arguments:
          - @kernel
          - %kernel.root_dir%

  happyr.mq2php.consumer_wrapper:
    class: Happyr\Mq2phpBundle\Service\ConsumerWrapper
    calls:
       - [setLogger, ["@?logger"]]
    arguments:
      - @simple_bus.asynchronous.standard_serialized_command_envelope_consumer
      - @simple_bus.asynchronous.standard_serialized_event_envelope_consumer
      - ~
      - ~