
services:
  happyr.mq2php.message_serializer:
    class: Happyr\Mq2phpBundle\Service\MessageSerializerDecorator
    configurator: [ "@happyr.mq2php.di.message_header_configurator" , configure]
    arguments: ["@happyr.mq2php.message_serializer.inner", ~]
    decorates: 'simple_bus.asynchronous.message_serializer'

  happyr.mq2php.di.message_header_configurator:
      class: Happyr\Mq2phpBundle\DependencyInjection\Configurator\MessageHeaderConfigurator
      public: false
      arguments:
          - @kernel
          - %kernel.root_dir%

  happyr.mq2php.consumer_wrapper:
    class: Happyr\Mq2phpBundle\Service\ConsumerWrapper
    calls:
       - [setLogger, ["@?logger"]]
    arguments:
      - ~
      - ~
      - "@?happyr.mq2php.extendable_command_envelope_consumer"
      - "@?happyr.mq2php.extendable_event_envelope_consumer"

  happyr.mq2php.extendable_command_envelope_consumer:
      class: Happyr\Mq2phpBundle\Consumer\ExtendableEnvelopeConsumer
      public: false
      arguments:
          - '@simple_bus.asynchronous.message_serializer'
          - ~
          - '@event_dispatcher'

  happyr.mq2php.extendable_event_envelope_consumer:
      class: Happyr\Mq2phpBundle\Consumer\ExtendableEnvelopeConsumer
      public: false
      arguments:
          - '@simple_bus.asynchronous.message_serializer'
          - ~
          - '@event_dispatcher'